[package]
name = "codspeed"
version = "1.0.0"
edition = "2021"
description = "Core instrumentation library for CodSpeed"
authors = ["Arthur Pastel <arthur@codspeed.io>"]
documentation = "https://docs.codspeed.io"
readme = "README.md"
repository = "https://github.com/CodSpeedHQ/codspeed-rust/crates/codspeed"
homepage = "https://codspeed.io"
license = "Apache-2.0"
categories = [
    "development-tools",
    "development-tools::profiling",
    "development-tools::testing",
]
keywords = ["codspeed", "benchmark"]

[dependencies]
colored = "2.0.0"
libc = "^0.2"

[[bench]]
name = "native"
harness = false
