[package]
name = "codspeed-criterion-compat"
version = "1.0.0"
edition = "2021"
description = "Criterion.rs compatibility layer for CodSpeed"
authors = ["Arthur Pastel <arthur@codspeed.io>"]
documentation = "https://docs.codspeed.io"
readme = "README.md"
repository = "https://github.com/CodSpeedHQ/codspeed-rust/crates/criterion_compat"
homepage = "https://codspeed.io"
license = "Apache-2.0"
categories = [
    "development-tools",
    "development-tools::profiling",
    "development-tools::testing",
]
keywords = ["codspeed", "benchmark", "criterion"]
[dependencies]
criterion = "0.4"
codspeed = { path = "../codspeed", version = "1.0.0" }
colored = "2.0.0"

[[bench]]
name = "criterion_example"
harness = false

[[bench]]
name = "criterion_integration_main"
harness = false

[[bench]]
name = "test_benches"
harness = false
