name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: blacksmith
    steps:
      - uses: actions/checkout@v3
      - uses: useblacksmith/rust-cache@v3
      - uses: pre-commit/action@v2.0.0
        with:
          extra_args: --all-files

  tests:
    runs-on: blacksmith
    steps:
      - uses: actions/checkout@v3
      - uses: useblacksmith/rust-cache@v3
      - run: cargo test --all

  compat-integration-test:
    runs-on: blacksmith
    steps:
      - uses: actions/checkout@v3
      - uses: useblacksmith/rust-cache@v3
        with:
          cache-target: release

      - run: cargo install --path crates/cargo-codspeed

      - run: cargo codspeed build -p codspeed
      - run: cargo codspeed build -p codspeed-bencher-compat
      - run: cargo codspeed build --features async_futures -p codspeed-criterion-compat

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@main
        with:
          run: cargo codspeed run
          token: ${{ secrets.CODSPEED_TOKEN }}
